Repository boostcampwm-2024/web22-LiBoo, pull requests merged in 2024-11, with the labels that each got.

#70 [STYLE] - 디자인 시스템 구축
  frontend/src/App.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/style.ts
  frontend/tsconfig.json
Labels: style

#76 [DESIGNE] HostPage 모달 구현
  frontend/index.html
  frontend/src/assets/download.svg
  frontend/src/assets/img_studio_obs.png
  frontend/src/components/host/OfflineView.tsx
  frontend/src/components/host/OnlineView.tsx
  frontend/src/components/host/Player.tsx
  frontend/src/components/host/Setting.tsx
  frontend/src/components/host/SettingForm.tsx
  frontend/src/components/host/SettingInfo.tsx
  frontend/src/components/host/StreamingStatus.tsx
  frontend/src/components/host/StreamingView.tsx
  frontend/src/hooks/useModal.ts
  frontend/src/hooks/usePortal.tsx
  frontend/tsconfig.json
Labels: fe

#75 [FEAT] client 페이지 초안 구현
  frontend/src/assets/play_icon.svg
  frontend/src/components/client/Chat.tsx
  frontend/src/components/client/ClientView.tsx
  frontend/src/components/client/Footer.tsx
  frontend/src/components/client/Header.tsx
  frontend/src/components/client/Player.tsx
  frontend/src/components/client/PlayerInfo.tsx
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/pages/ClientPage.tsx
  frontend/src/styles/theme.ts
Labels: enhancement, fe

#103 [FEAT] 클라이언트 페이지 영상 송출
  frontend/package.json
  frontend/src/assets/custom_play_icon.svg
  frontend/src/assets/icons/pause_icon.svg
  frontend/src/assets/icons/play_icon.svg
  frontend/src/components/client/Chat.tsx
  frontend/src/components/client/ClientView.tsx
  frontend/src/components/client/Player.tsx
  frontend/src/components/client/index.ts
  frontend/src/pages/ClientPage.tsx
  yarn.lock
Labels: FEAT, FE🎄

#102 [CHORE] remote 환경 구성
  .github/workflows/pr-slack-notify.yml
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/apis/index.ts
  frontend/tsconfig.json
  yarn.lock
Labels: CHORE, FE🎄

#98 [FEAT] 채팅방 컴포넌트 기본 퍼블리싱
  frontend/src/assets/icons/check.svg
  frontend/src/assets/icons/close.svg
  frontend/src/assets/icons/out.svg
  frontend/src/assets/icons/question.svg
  frontend/src/assets/icons/send.svg
  frontend/src/assets/icons/speech-bubble.svg
  frontend/src/assets/icons/three-point.svg
  frontend/src/components/chat/ChatHeader.tsx
  frontend/src/components/chat/ChatInput.tsx
  frontend/src/components/chat/ChatList.tsx
  frontend/src/components/chat/ChatQuestionSection.tsx
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/chat/LayerPopup.tsx
  frontend/src/components/chat/NoticeCard.tsx
  frontend/src/components/chat/QuestionCard.tsx
  frontend/src/components/chat/index.ts
  frontend/src/index.css
Labels: FEAT, FE🎄

#108 [Feat] 아이콘 수정 및 스페이스 키 눌렀을 때 정지, 재생 아이콘 보이게
  frontend/src/assets/icons/custom_play_icon.svg
  frontend/src/assets/icons/live_pause_icon.svg
  frontend/src/assets/icons/pause_icon.svg
  frontend/src/assets/icons/play_icon.svg
  frontend/src/components/client/Player.tsx
Labels: FEAT, FE🎄

#109 [FEAT] 호스트 페이지 모달 api 연동
  frontend/package.json
  frontend/src/apis/host/fetchStreamKey.ts
  frontend/src/apis/index.ts
  frontend/src/components/host/Chat.tsx
  frontend/src/components/host/SettingInfo.tsx
  frontend/src/components/host/index.ts
  frontend/src/queries/host/useFetchStreamKey.ts
  frontend/src/utils/id.ts
  frontend/tsconfig.json
  yarn.lock
Labels: FEAT, FE🎄

#130 [FEAT] mainPage header 구현
  frontend/index.html
  frontend/public/pabicon.ico
  frontend/src/assets/icons/search_icon.svg
  frontend/src/assets/icons/video_icon.svg
  frontend/src/components/main/MainHeader.tsx
Labels: FEAT, FE🎄

#139 [CICD] FE 코드 배포
  frontend/index.html
  frontend/public/pabicon.ico
  frontend/src/App.tsx
  frontend/src/apis/fetchBroadcastStatus.ts
  frontend/src/apis/queries/host/useBroadcastStatusPolling.ts
  frontend/src/apis/queries/host/useUpdateHost.ts
  frontend/src/apis/updateHost.ts
  frontend/src/assets/icons/search_icon.svg
  frontend/src/assets/icons/video_icon.svg
  frontend/src/assets/logo.gif
  frontend/src/components/host/Header.tsx
  frontend/src/components/host/Player.tsx
  frontend/src/components/host/Setting.tsx
  frontend/src/components/host/SettingForm.tsx
  frontend/src/components/host/SettingInfo.tsx
  frontend/src/components/host/StreamingStatus.tsx
  frontend/src/components/main/MainHeader.tsx
  frontend/src/utils/streamKey.ts
Labels: FE🎄

#143 [FEAT] 라이브 중인 방송에 대한 정보 전달 API
  backend/mainServer/src/app.module.ts
  backend/mainServer/src/dto/liveSessionDto.ts
  backend/mainServer/src/dto/memoryDbDto.ts
  backend/mainServer/src/host/host.controller.ts
  backend/mainServer/src/memory-db/memory-db.service.ts
  backend/mainServer/src/streams/streams.controller.spec.ts
  backend/mainServer/src/streams/streams.controller.ts
  backend/mainServer/src/streams/streams.module.ts
  backend/mainServer/src/streams/streams.service.spec.ts
  backend/mainServer/src/streams/streams.service.ts
  backend/mainServer/src/viewer/viewer.controller.ts
  backend/mainServer/src/viewer/viewer.module.ts
Labels: FEAT, BE🐹

#142 [FEAT] 메인페이지 라이브영상 송출
  frontend/src/apis/fetchMainLive.ts
  frontend/src/apis/queries/main/useFetchMainLive.ts
  frontend/src/assets/sample_profile.png
  frontend/src/components/main/MainHeader.tsx
  frontend/src/components/main/RecommendLive.tsx
  frontend/src/pages/MainPage.tsx
Labels: FEAT, FE🎄

#149 [FEAT] id 생성 고차함수 구현 및 기존 관련 id 사용 로직 리팩토링
  frontend/src/App.tsx
  frontend/src/apis/fetchBroadcastStatus.ts
  frontend/src/apis/queries/host/useBroadcastStatusPolling.ts
  frontend/src/components/host/Setting.tsx
  frontend/src/components/host/SettingInfo.tsx
  frontend/src/hocs/withUserId.tsx
  frontend/src/utils/id.ts
  frontend/tsconfig.json
Labels: FEAT, FE🎄

#148 [FEAT] 채팅방 소켓 세팅 및 버튼 인터렉션 추가
  frontend/eslint.config.js
  frontend/package.json
  frontend/src/components/chat/ChatHeader.tsx
  frontend/src/components/chat/ChatInput.tsx
  frontend/src/components/chat/ChatList.tsx
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/chat/LayerPopup.tsx
  frontend/src/components/chat/NoticeCard.tsx
  frontend/src/constants/chat.ts
  frontend/src/contexts/chatContext.tsx
  frontend/src/type/chat.ts
  frontend/src/utils/createSocket.ts
  frontend/tsconfig.json
  yarn.lock
Labels: FEAT, FE🎄

#158 [FEAT] 움직이는 배너 구현
  frontend/index.html
  frontend/package.json
  frontend/src/components/main/ServiceBanner.tsx
  frontend/src/index.css
  yarn.lock
Labels: FEAT, DESIGN, FE🎄

#159 [FEAT] 메인페이지에서 라이브 영상 재생
  frontend/src/apis/fetchMainLive.ts
  frontend/src/apis/fetchRecentLive.ts
  frontend/src/apis/queries/main/useFetchMainLive.ts
  frontend/src/apis/queries/main/useFetchRecentLive.ts
  frontend/src/components/client/ClientView.tsx
  frontend/src/components/main/LiveVideoCard.tsx
  frontend/src/components/main/MainLiveSection.tsx
  frontend/src/components/main/RecommendLive.tsx
  frontend/src/components/main/ReplayVideoCard.tsx
  frontend/src/type/live.ts
Labels: FEAT, FE🎄

#156 [FEAT] 미리보기 파일 추가 시 수정 삭제 버튼 구현
  frontend/src/components/host/SettingForm.tsx
  frontend/src/utils/convertToBase64.ts
Labels: FEAT, FE🎄

#167 [FEAT] client 페이지에 데이터 페칭
  frontend/src/apis/fetchLive.ts
  frontend/src/apis/fetchRecentLive.ts
  frontend/src/apis/queries/client/useFetchLive.ts
  frontend/src/components/client/ClientView.tsx
  frontend/src/components/client/PlayerInfo.tsx
  frontend/src/components/common/ServiceBanner.tsx
  frontend/src/components/common/ShowInfoBadge.tsx
  frontend/src/components/main/LiveVideoCard.tsx
  frontend/src/components/main/ReplayVideoCard.tsx
  frontend/src/components/main/index.ts
  frontend/src/pages/MainPage.tsx
  frontend/src/type/live.ts
  frontend/src/utils/updateElapsedTime.ts
  frontend/tsconfig.json
Labels: FEAT, FE🎄

#168 [FEAT] 호스트 페이지 렌더링 최적화
  frontend/package.json
  frontend/src/apis/queries/host/useUpdateHost.ts
  frontend/src/apis/updateHost.ts
  frontend/src/components/host/Form/CategoryField.tsx
  frontend/src/components/host/Form/HostNameField.tsx
  frontend/src/components/host/Form/ImageField.tsx
  frontend/src/components/host/Form/LiveTitleField.tsx
  frontend/src/components/host/Form/NoticeField.tsx
  frontend/src/components/host/Form/TagField.tsx
  frontend/src/components/host/Form/index.ts
  frontend/src/components/host/Form/style.tsx
  frontend/src/components/host/SettingForm.tsx
  frontend/src/type/hostInfo.ts
  yarn.lock
Labels: FEAT, FE🎄

#169 [FEAT] 채팅 서버 구현
  backend/chatServer/.eslintrc.js
  backend/chatServer/.gitignore
  backend/chatServer/README.md
  backend/chatServer/babel.config.json
  backend/chatServer/dockerfile
  backend/chatServer/nest-cli.json
  backend/chatServer/package.json
  backend/chatServer/src/app.module.ts
  backend/chatServer/src/chat/chat.gateway.spec.ts
  backend/chatServer/src/chat/chat.gateway.ts
  backend/chatServer/src/chat/chat.module.ts
  backend/chatServer/src/event/constants.ts
  backend/chatServer/src/event/dto/IncomingMessage.dto.ts
  backend/chatServer/src/event/dto/JoiningRoom.dto.ts
  backend/chatServer/src/event/dto/OutgoingMessage.dto.ts
  backend/chatServer/src/main.ts
  backend/chatServer/src/room/room.service.ts
  backend/chatServer/src/user/user.interface.ts
  backend/chatServer/src/user/user.module.ts
  backend/chatServer/src/user/user.repository.ts
  backend/chatServer/src/user/user.service.spec.ts
  backend/chatServer/src/user/user.service.ts
  backend/chatServer/src/utils/random.ts
  backend/chatServer/test/app.e2e-spec.ts
  backend/chatServer/test/jest-e2e.json
  backend/chatServer/tsconfig.json
  backend/package.json
  be.build.yaml
  nginx/conf.d/api.conf
  nginx/conf.d/chat.conf
  yarn.lock
Labels: FEAT, BE🐹

#174 [CHORE] 라이브 중인 방송들이 최상위로 올라올 수 있도록 코드 수정
  backend/mainServer/src/memory-db/memory-db.service.ts
Labels: CHORE, BE🐹

#175 [FEAT] 채팅 서버 연결 및 고도화 기능 구현
  frontend/src/assets/icons/speaker.svg
  frontend/src/components/chat/ChatHeader.tsx
  frontend/src/components/chat/ChatInput.tsx
  frontend/src/components/chat/ChatList.tsx
  frontend/src/components/chat/ChatQuestionSection.tsx
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/chat/QuestionCard.tsx
  frontend/src/constants/chat.ts
  frontend/src/pages/ClientPage.tsx
  frontend/src/pages/HostPage.tsx
  frontend/src/type/chat.ts
  frontend/src/type/user.ts
Labels: FEAT, FE🎄

#179 [FEAT] host 페이지 id 라우팅 추가
  frontend/src/App.tsx
  frontend/src/components/common/Header.tsx
  frontend/src/components/host/HostRedirect.tsx
  frontend/src/components/host/index.ts
Labels: FEAT, FE🎄

#185 [FIX] 호스트 페이지에서 채팅방 입장을위한 sessionKey 초기화 추가
  frontend/src/components/chat/ChatInput.tsx
  frontend/src/components/chat/HostChatRoom.tsx
  frontend/src/pages/HostPage.tsx
Labels: FIX, FE🎄

#187 [FIX] 세션 키 최신화하여 api 요청
  frontend/src/components/host/Setting.tsx
Labels: FIX, FE🎄

#188 [REFACTOR] 불필요한 채팅방 리렌더링 개선
  frontend/src/components/chat/ChatHeader.tsx
Labels: REFACTOR

#200 [FEAT] video 커스텀 구현 및 적용
  frontend/src/components/client/ClientView.tsx
  frontend/src/components/client/Player.tsx
  frontend/src/components/common/Header.tsx
  frontend/src/components/host/OnlineView.tsx
  frontend/src/components/host/Setting.tsx
  frontend/src/components/host/StreamingDisplay.tsx
  frontend/src/components/main/RecommendList.tsx
  frontend/src/components/main/RecommendLive.tsx
  frontend/src/hooks/usePlayer.ts
  frontend/src/hooks/useRotatePlayer.ts
  frontend/src/pages/ClientPage.tsx
  frontend/src/utils/getVideoURL.ts
Labels: FEAT, FE🎄

#201 [FEAT] Shared Worker를 통한 다중탭 소켓 공유 구현
  frontend/src/components/chat/ChatInput.tsx
  frontend/src/components/chat/ChatQuestionSection.tsx
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/components/chat/ChatRoomLayout.tsx
  frontend/src/components/chat/ClientChatRoom.tsx
  frontend/src/components/chat/HostChatRoom.tsx
  frontend/src/components/chat/index.ts
  frontend/src/hooks/useChatRoom.ts
  frontend/src/pages/ClientPage.tsx
  frontend/src/pages/HostPage.tsx
  frontend/src/utils/chatWorker.ts
Labels: FEAT, FE🎄

#202 [FEAT] 마우스 호버 시 플레이어 재생
  frontend/src/components/main/LiveVideoCard.tsx
Labels: FEAT, FE🎄

#199 [FEAT] 영상 세그먼트 키프레임 고정 및 다시보기 영상 최신/단일 데이터 API 작성
  backend/mainServer/src/app.module.ts
  backend/mainServer/src/common/constants.ts
  backend/mainServer/src/common/transformers.ts
  backend/mainServer/src/common/util.ts
  backend/mainServer/src/dto/memoryDbDto.ts
  backend/mainServer/src/dto/replayVideoDto.ts
  backend/mainServer/src/host/host.controller.ts
  backend/mainServer/src/host/host.service.ts
  backend/mainServer/src/memory-db/memory-db.service.ts
  backend/mainServer/src/mock-data/mock-data.service.ts
  backend/mainServer/src/replay/replay.controller.spec.ts
  backend/mainServer/src/replay/replay.controller.ts
  backend/mainServer/src/replay/replay.module.ts
  backend/mainServer/src/replay/replay.service.spec.ts
  backend/mainServer/src/replay/replay.service.ts
  backend/mainServer/src/streams/streams.controller.ts
  backend/rtmpServer/package.json
  backend/rtmpServer/src/index.ts
  yarn.lock
Labels: FEAT, BE🐹

#205 [FEAT] 채팅 오토스크롤 버튼 구현
  frontend/src/components/chat/ChatAutoScroll.tsx
  frontend/src/components/chat/ChatList.tsx
  frontend/src/components/chat/ChatRoomLayout.tsx
  frontend/src/components/chat/ClientChatRoom.tsx
  frontend/src/components/chat/HostChatRoom.tsx
Labels: FEAT, FE🎄

#210 [FIX] 방송 신호에 따라 다시보기 상태를 전환하도록 코드 수정
  backend/mainServer/src/host/host.controller.ts
Labels: FIX, BE🐹

#212 [DESIGN] 서비스배너 gradient 값 수정
  frontend/src/components/common/ServiceBanner.tsx
Labels: DESIGN

#214 [REFACTOR] 클라이언트 페이지 스트리밍 재생 렌더링 최적화
  frontend/src/components/client/ElapsedTime.tsx
  frontend/src/components/client/PlayerInfo.tsx
  frontend/src/pages/ReplayPage.tsx
Labels: REFACTOR, FE🎄

#224 [FEAT] 채팅창 디자인 개선 및 기능 추가
  frontend/src/assets/icons/question_user_icon.svg
  frontend/src/components/chat/ChatAutoScroll.tsx
  frontend/src/components/chat/ChatInput.tsx
  frontend/src/components/chat/ChatList.tsx
  frontend/src/components/chat/ChatQuestionSection.tsx
  frontend/src/components/chat/ChatRoomLayout.tsx
  frontend/src/components/chat/QuestionCard.tsx
Labels: FEAT, DESIGN, FE🎄

#226 [FEAT] player custom
  frontend/eslint.config.js
  frontend/package.json
  frontend/src/components/client/Player.tsx
  frontend/src/components/client/VideoPlayer.tsx
  frontend/src/components/client/video/ControlsOverlay/ControlsOverlay.tsx
  frontend/src/components/client/video/ControlsOverlay/FullscreenButton.tsx
  frontend/src/components/client/video/ControlsOverlay/PlayPauseButton.tsx
  frontend/src/components/client/video/ControlsOverlay/TimeDisplay.tsx
  frontend/src/components/client/video/ControlsOverlay/VolumeControl.tsx
  frontend/src/components/client/video/InformationOverlay/ChatButton.tsx
  frontend/src/components/client/video/InformationOverlay/InformationOverlay.tsx
  frontend/src/components/client/video/InformationOverlay/LiveBadge.tsx
  frontend/src/components/client/video/ProgressBar/BufferedProgress.tsx
  frontend/src/components/client/video/ProgressBar/CurrentProgress.tsx
  frontend/src/components/client/video/ProgressBar/LiveProgress.tsx
  frontend/src/components/client/video/ProgressBar/PreviewThumbnail.tsx
  frontend/src/components/client/video/ProgressBar/ProgressBar.tsx
  frontend/src/components/client/video/ProgressBar/ProgressHandle.tsx
  frontend/src/components/client/video/Video.tsx
  frontend/src/components/client/video/VideoPlayer.tsx
  frontend/src/components/client/video/index.ts
  frontend/src/contexts/VideoContext.tsx
  frontend/src/hooks/usePlayer.ts
  frontend/src/hooks/useVideoPlayer.ts
  frontend/src/hooks/useVideoPlayer/index.ts
  frontend/src/hooks/useVideoPlayer/useHLSPlayer.ts
  frontend/src/hooks/useVideoPlayer/useVideoControls.ts
  frontend/src/hooks/useVideoPlayer/useVideoEvents.ts
  frontend/src/reducers/actionCreators.ts
  frontend/src/reducers/controlsReducer.ts
  frontend/src/reducers/videoPlayerReducer.ts
  frontend/src/type/video.ts
  frontend/src/utils/progress.ts
  frontend/src/utils/time.ts
  frontend/src/utils/volume.ts
  frontend/tsconfig.json
  yarn.lock
Labels: FEAT, FE🎄

#232 [FEAT] suspense와 errorboundary 구현 및 통합
  frontend/package.json
  frontend/src/apis/queries/main/useFetchMainLive.ts
  frontend/src/apis/queries/main/useFetchRecentLive.ts
  frontend/src/apis/queries/main/useFetchRecentReplay.ts
  frontend/src/components/common/AsyncBoundary.tsx
  frontend/src/components/error/RecommendLiveError.tsx
  frontend/src/components/error/index.ts
  frontend/src/components/main/MainLiveSection.tsx
  frontend/src/components/main/MainReplaySection.tsx
  frontend/src/components/main/RecommendLive.tsx
  frontend/src/components/skeleton/RecommendLiveSkeleton.tsx
  frontend/src/components/skeleton/index.ts
  frontend/src/constants/recommendLive.ts
  frontend/src/pages/ClientPage.tsx
  frontend/src/pages/MainPage.tsx
  yarn.lock
Labels: FEAT, FE🎄

#240 [REFACTOR] 채팅창 컴포넌트 렌더링 최적화 및 비제어 컴포넌트로 개선
  frontend/src/components/chat/ChatHeader.tsx
  frontend/src/components/chat/ChatInput.tsx
  frontend/src/components/chat/ChatList.tsx
  frontend/src/components/chat/ChatQuestionSection.tsx
  frontend/src/components/chat/ChatRoomLayout.tsx
  frontend/src/components/chat/ClientChatRoom.tsx
  frontend/src/components/chat/HostChatRoom.tsx
  frontend/src/components/chat/QuestionCard.tsx
  frontend/src/components/client/ElapsedTime.tsx
  frontend/src/utils/formatTimeDifference.ts
Labels: REFACTOR, FE🎄

#241 [FEAT] 치지직 라이브 영상에 맞춰 mock 데이터 대응 / 다시보기 m3u8 저장 로직 수정
  backend/mainServer/src/common/constants.ts
  backend/mainServer/src/common/crawler.ts
  backend/mainServer/src/common/util.ts
  backend/mainServer/src/host/host.controller.ts
  backend/mainServer/src/memory-db/memory-db.service.ts
  backend/mainServer/src/mock-data/mock-data.controller.ts
  backend/mainServer/src/replay/replay.controller.ts
Labels: FEAT, BE🐹

#239 [REFACTOR] 플레이어 랜더링 개선 및 메인 효과 추가
  frontend/src/components/common/ServiceBanner.tsx
  frontend/src/components/main/AnimatedLiveHeader.tsx
  frontend/src/components/main/AnimatedProfileSection.tsx
  frontend/src/components/main/MiniPlayerItem.tsx
  frontend/src/components/main/RecommendList.tsx
  frontend/src/components/main/RecommendLive.tsx
  frontend/src/constants/bannerKeywords.ts
Labels: FEAT, DESIGN, FE🎄
