Repository boostcampwm-2024/web22-LiBoo, pull requests merged in 2024-12, with the labels that each got.

#256 [FEAT] 에러페이지 적용
  frontend/src/App.tsx
  frontend/src/apis/checkLiveExist.ts
  frontend/src/apis/checkReplayExist.ts
  frontend/src/apis/fetchLive.ts
  frontend/src/apis/fetchReplay.ts
  frontend/src/apis/queries/client/useCheckLiveExist.ts
  frontend/src/apis/queries/client/useFetchLive.ts
  frontend/src/apis/queries/replay/useCheckReplayExist.ts
  frontend/src/apis/queries/replay/useFetchReplay.ts
  frontend/src/assets/icons/warning_icon.svg
  frontend/src/components/client/Chat.tsx
  frontend/src/components/client/ClientView.tsx
  frontend/src/components/client/PlayerInfo.tsx
  frontend/src/components/client/index.ts
  frontend/src/components/common/AsyncBoundary.tsx
  frontend/src/components/common/Header.tsx
  frontend/src/components/error/PlayerStreamError.tsx
  frontend/src/components/error/index.ts
  frontend/src/components/main/MainLiveSection.tsx
  frontend/src/components/main/MainReplaySection.tsx
  frontend/src/components/replay/PlayerInfo.tsx
  frontend/src/components/replay/ReplayView.tsx
  frontend/src/hocs/withLiveExistCheck.tsx
  frontend/src/hocs/withReplayExistCheck.tsx
  frontend/src/pages/ClientPage.tsx
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/ReplayPage.tsx
  frontend/src/pages/index.ts
  frontend/src/type/live.ts
  frontend/src/type/replay.ts
Labels: FEAT, FE🎄

#266 [FEAT] 호스트의 채팅 유저 차단 기능 구현 및 채팅 예외처리
  frontend/src/assets/icons/user-block.svg
  frontend/src/components/chat/ChatInput.tsx
  frontend/src/components/chat/ChatList.tsx
  frontend/src/components/chat/ChatRoomLayout.tsx
  frontend/src/components/chat/UserInfoCard.tsx
  frontend/src/components/common/ConfirmModal.tsx
  frontend/src/constants/chat.ts
  frontend/src/contexts/chatContext.tsx
  frontend/src/hooks/useChatRoom.ts
  frontend/src/type/chat.ts
  frontend/src/utils/chatWorker.ts
  frontend/src/utils/createSocket.ts
  frontend/src/utils/parseDate.ts
Labels: FEAT, FE🎄

#277 [REFACTOR] ChatInput 비제어 컴포넌트로 렌더링 최적화
  frontend/src/components/chat/ChatInput.tsx
  frontend/src/components/chat/ChatList.tsx
  frontend/src/components/chat/ChatRoomLayout.tsx
Labels: REFACTOR, FE🎄

#276 [FEAT] 썸네일 API URL 추가 / 다시보기 등록 기준으로 정렬
  backend/mainServer/src/host/host.controller.ts
  backend/mainServer/src/memory-db/memory-db.service.ts
  backend/rtmpServer/package.json
  backend/rtmpServer/src/types/index.d.ts
  backend/rtmpServer/tsconfig.json
  yarn.lock
Labels: REFACTOR, BE🐹

#288 [FEAT] 404 에러 처리 및 세션키로 변경
  frontend/src/hooks/usePlayer.ts
  frontend/src/utils/hostURL.ts
Labels: FIX, FE🎄
